### ISSUE TITLE
CodeSnippetsForCBEditor

### ISSUE THREAD

**Issue by sdavidg** [Odyseus/CustomButtons#1]
Hello, I installed the "CodeSnippetsForCBEditor" (http://odyseus.github.io/CustomButtons/CodeSnippetsForCBEditor.html) button and I would adapt to the firebug console. Any idea how to capture the opening of Firebug? It would be something like: Services.obs.addObserver (observer, "????", false) ;?
I would do something like: "https://addons.mozilla.org/es/firefox/addon/firebugsnippets/"

Thank You

**Comment by Odyseus** [comment]
Hello, sdavidg. Sorry for the delay.

If you use Firebug detached, you could use the same event in the observer.

Example:

``` Javascript
var observer = {
    observe : function (subject, topic, data) {
        subject.addEventListener("load", this, false);
    },
    handleEvent : function (aEvt) {
        var doc = aEvt.target;
        var win = doc.defaultView;
        win.removeEventListener("load", this, false);
        if (doc.location.href !== "chrome://firebug/content/firefox/firebug.xul")
            return;
        // Code to attach the button to the Firebug window.
    }
};

Services.obs.addObserver(observer, "domwindowopened", false);
```

I don't know which event is triggered (if any) when the Firebug interface is attached to the main window.

An alternative way, and I thing a simpler way, would be to attach an "onclick" event to the Firebug button that would attach the "snippets button" anywhere in the Firebug toolbar. If the "snippets button" exists, do nothing. If it doesn't exists, create it and attach it.

Sorry if I can't be of more help.

**Comment by sdavidg** [comment]
Thanks for the help.
Finally I created a button with data from the database.
To insert the script in Firebug I used the following code:

``` javascript
this.pasteItem = function(text) {
    AcebugEditor = Firebug.Ace && Firebug.Ace.win2 && Firebug.Ace.win2.editor;
    if(AcebugEditor)
    {
        AcebugEditor.insert(text);
    }
    else
    {
        Firebug.CommandEditor.setText(text);
    }
}
```

It is the same code used in firebugsnippets.
I will post the code when I have finished, for now looks like this:
![sin titulo](https://cloud.githubusercontent.com/assets/4955944/6842097/288836b6-d394-11e4-9b40-e5569722409e.png)

Thanks
